import type { Paint, QrDesign } from './types';

const solid = (color: string): Paint => ({ type: 'solid', color });
const linear = (angle: number, ...colors: string[]): Paint => ({
  type: 'linear',
  angle,
  stops: colors.map((color, i) => ({ offset: colors.length === 1 ? 0 : i / (colors.length - 1), color })),
});
const radial = (...colors: string[]): Paint => ({
  type: 'radial',
  stops: colors.map((color, i) => ({ offset: colors.length === 1 ? 0 : i / (colors.length - 1), color })),
});

const WHITE = solid('#FFFFFF');
const INK = solid('#0F172A');

/**
 * גלריית העיצובים.
 *
 * כל עיצוב מתואר בווקטורים ויחידות מודול בלבד — ולכן נשאר חד ומאוזן
 * בכל גודל פלט, מאייקון 256px ועד כרזת A4 ב-300DPI.
 */
export const DESIGNS: QrDesign[] = [
  {
    id: 'classic',
    name: 'קלאסי',
    blurb: 'ריבועים חדים, שחור על לבן — התאימות הגבוהה ביותר לכל סורק',
    tags: ['נקי', 'עסקי', 'הדפסה'],
    moduleShape: 'square',
    eyeFrame: 'square',
    eyeBall: 'square',
    dotScale: 1,
    body: INK,
    eyeFramePaint: INK,
    eyeBallPaint: INK,
    background: WHITE,
    quietZone: 4,
    cornerRadius: 0,
    frameStyle: 'bottomBar',
    frameBarPaint: INK,
    frameTextPaint: WHITE,
    ecLevel: 'M',
    previewBg: '#FFFFFF',
  },
  {
    id: 'soft-dots',
    name: 'נקודות רכות',
    blurb: 'עיגולים אווריריים ועיני טבעת — עדין, מודרני ונעים לעין',
    tags: ['עדין', 'מודרני'],
    moduleShape: 'dot',
    eyeFrame: 'circle',
    eyeBall: 'circle',
    dotScale: 1,
    body: solid('#1E293B'),
    eyeFramePaint: solid('#1E293B'),
    eyeBallPaint: solid('#1E293B'),
    background: WHITE,
    quietZone: 4,
    cornerRadius: 0.06,
    frameStyle: 'pill',
    frameBarPaint: solid('#1E293B'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FFFFFF',
  },
  {
    id: 'violet-flow',
    name: 'זרימה סגולה',
    blurb: 'מודולים מתמזגים בגרדיאנט סגול-אינדיגו — חתימה ויזואלית חזקה',
    tags: ['גרדיאנט', 'יצירתי', 'מומלץ'],
    moduleShape: 'fluid',
    eyeFrame: 'rounded',
    eyeBall: 'rounded',
    dotScale: 1,
    body: linear(135, '#7C3AED', '#4338CA'),
    eyeFramePaint: linear(135, '#7C3AED', '#4338CA'),
    eyeBallPaint: solid('#4338CA'),
    background: WHITE,
    quietZone: 4,
    cornerRadius: 0.08,
    frameStyle: 'bottomBar',
    frameBarPaint: linear(90, '#7C3AED', '#4338CA'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FFFFFF',
  },
  {
    id: 'neon-night',
    name: 'ניאון לילה',
    blurb: 'נקודות ציאן-סגול על כהה עמוק — בולט על מסכים ובסטוריז',
    tags: ['כהה', 'ניאון', 'דיגיטל'],
    moduleShape: 'dot',
    eyeFrame: 'rounded',
    eyeBall: 'rounded',
    dotScale: 1,
    body: linear(135, '#22D3EE', '#A78BFA'),
    eyeFramePaint: solid('#22D3EE'),
    eyeBallPaint: solid('#A78BFA'),
    background: solid('#0B1120'),
    quietZone: 4,
    cornerRadius: 0.1,
    plate: { strokePaint: solid('#1E293B'), width: 0.4, inset: 1.2 },
    frameStyle: 'pill',
    frameBarPaint: linear(90, '#22D3EE', '#A78BFA'),
    frameTextPaint: solid('#0B1120'),
    ecLevel: 'Q',
    previewBg: '#0B1120',
  },
  {
    id: 'ink-drop',
    name: 'טיפת דיו',
    blurb: 'צורה אורגנית רציפה עם עיני עלה — נראה מצויר ביד',
    tags: ['אורגני', 'אמנותי'],
    moduleShape: 'fluid',
    eyeFrame: 'leaf',
    eyeBall: 'leaf',
    dotScale: 1,
    body: solid('#111827'),
    eyeFramePaint: solid('#111827'),
    eyeBallPaint: solid('#111827'),
    background: solid('#FAF7F2'),
    quietZone: 4,
    cornerRadius: 0.12,
    frameStyle: 'ribbon',
    frameBarPaint: solid('#111827'),
    frameTextPaint: solid('#FAF7F2'),
    ecLevel: 'Q',
    previewBg: '#FAF7F2',
  },
  {
    id: 'rain',
    name: 'גשם',
    blurb: 'פסים אנכיים מחוברים — קצבי, קריא ומאוד ייחודי',
    tags: ['פסים', 'מינימלי'],
    moduleShape: 'vbars',
    eyeFrame: 'rounded',
    eyeBall: 'rounded',
    dotScale: 0.95,
    body: solid('#0F766E'),
    eyeFramePaint: solid('#0F766E'),
    eyeBallPaint: solid('#0F766E'),
    background: WHITE,
    quietZone: 4,
    cornerRadius: 0.06,
    frameStyle: 'bottomBar',
    frameBarPaint: solid('#0F766E'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FFFFFF',
  },
  {
    id: 'sunset',
    name: 'שקיעה',
    blurb: 'פסים אופקיים בגרדיאנט כתום-ורוד — חם ואנרגטי',
    tags: ['גרדיאנט', 'פסים', 'חם'],
    moduleShape: 'hbars',
    eyeFrame: 'rounded',
    eyeBall: 'rounded',
    dotScale: 0.94,
    body: linear(0, '#C2410C', '#BE185D'),
    eyeFramePaint: linear(0, '#C2410C', '#BE185D'),
    eyeBallPaint: solid('#BE185D'),
    background: solid('#FFF7ED'),
    quietZone: 4,
    cornerRadius: 0.1,
    frameStyle: 'pill',
    frameBarPaint: linear(0, '#C2410C', '#BE185D'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FFF7ED',
  },
  {
    id: 'emerald-gem',
    name: 'אבן חן',
    blurb: 'מעוינים בגוני אמרלד עם עיני יהלום — יוקרתי ומדויק',
    tags: ['מעוין', 'יוקרתי'],
    moduleShape: 'diamond',
    eyeFrame: 'cut',
    eyeBall: 'rounded',
    dotScale: 1,
    body: linear(135, '#047857', '#064E3B'),
    eyeFramePaint: solid('#065F46'),
    eyeBallPaint: linear(135, '#047857', '#064E3B'),
    background: WHITE,
    quietZone: 4,
    cornerRadius: 0.04,
    frameStyle: 'bottomBar',
    frameBarPaint: solid('#047857'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FFFFFF',
  },
  {
    id: 'gold-noir',
    name: 'זהב על שחור',
    blurb: 'מודולים אלכסוניים בזהב על פחם, עם מסגרת דקה — מזמין ויוקרתי',
    tags: ['כהה', 'יוקרתי', 'אירועים'],
    moduleShape: 'classy',
    eyeFrame: 'cut',
    eyeBall: 'square',
    dotScale: 1,
    body: linear(135, '#FDE68A', '#D4AF37'),
    eyeFramePaint: solid('#D4AF37'),
    eyeBallPaint: solid('#FDE68A'),
    background: solid('#111111'),
    quietZone: 4.5,
    cornerRadius: 0.03,
    plate: { strokePaint: solid('#D4AF37'), width: 0.28, inset: 1.4 },
    frameStyle: 'outline',
    frameBarPaint: solid('#111111'),
    frameTextPaint: solid('#D4AF37'),
    ecLevel: 'Q',
    previewBg: '#111111',
  },
  {
    id: 'pastel',
    name: 'פסטל',
    blurb: 'ריבועים מעוגלים בלבנדר-ורוד — רך, ידידותי ומזמין',
    tags: ['רך', 'צבעוני'],
    moduleShape: 'rounded',
    eyeFrame: 'rounded',
    eyeBall: 'flower',
    dotScale: 0.97,
    body: linear(135, '#7C3AED', '#BE185D'),
    eyeFramePaint: solid('#7C3AED'),
    eyeBallPaint: solid('#BE185D'),
    background: solid('#FDF4FF'),
    quietZone: 4,
    cornerRadius: 0.14,
    frameStyle: 'pill',
    frameBarPaint: linear(135, '#7C3AED', '#BE185D'),
    frameTextPaint: WHITE,
    ecLevel: 'Q',
    previewBg: '#FDF4FF',
  },
  {
    id: 'sparks',
    name: 'ניצוצות',
    blurb: 'ניצוצות ארבע-קצוות בגרדיאנט מג׳נטה — חגיגי ובלתי נשכח',
    tags: ['שובב', 'אירועים'],
    moduleShape: 'star',
    eyeFrame: 'shield',
    eyeBall: 'flower',
    dotScale: 1,
    body: linear(135, '#E11D48', '#B45309'),
    eyeFramePaint: solid('#E11D48'),
    eyeBallPaint: solid('#B45309'),
    background: solid('#FFFBEB'),
    quietZone: 4,
    cornerRadius: 0.12,
    frameStyle: 'ribbon',
    frameBarPaint: linear(0, '#E11D48', '#B45309'),
    frameTextPaint: WHITE,
    ecLevel: 'H',
    previewBg: '#FFFBEB',
  },
  {
    id: 'blueprint',
    name: 'שרטוט',
    blurb: 'צלבים לבנים על כחול הנדסי עם מסגרת מקווקוות — טכני ומגניב',
    tags: ['כהה', 'טכני'],
    moduleShape: 'plus',
    eyeFrame: 'square',
    eyeBall: 'square',
    dotScale: 1,
    body: solid('#E0F2FE'),
    eyeFramePaint: solid('#E0F2FE'),
    eyeBallPaint: solid('#38BDF8'),
    background: solid('#0C4A6E'),
    quietZone: 4.5,
    cornerRadius: 0.02,
    plate: { strokePaint: solid('#7DD3FC'), width: 0.22, inset: 1.6, dashed: true },
    frameStyle: 'ticket',
    frameBarPaint: solid('#0C4A6E'),
    frameTextPaint: solid('#7DD3FC'),
    ecLevel: 'H',
    previewBg: '#0C4A6E',
  },
  {
    id: 'oled',
    name: 'הפוך',
    blurb: 'לבן על שחור מוחלט — חוסך סוללה ונראה מעולה במצב כהה',
    tags: ['כהה', 'מסך'],
    moduleShape: 'rounded',
    eyeFrame: 'rounded',
    eyeBall: 'rounded',
    dotScale: 0.97,
    body: solid('#F8FAFC'),
    eyeFramePaint: solid('#F8FAFC'),
    eyeBallPaint: solid('#F8FAFC'),
    background: solid('#000000'),
    quietZone: 4,
    cornerRadius: 0.1,
    frameStyle: 'bottomBar',
    frameBarPaint: solid('#F8FAFC'),
    frameTextPaint: solid('#000000'),
    ecLevel: 'Q',
    previewBg: '#000000',
  },
  {
    id: 'mint-outline',
    name: 'מנטה',
    blurb: 'ריבועים מעוגלים בירוק רענן עם קו מתאר עדין — נקי ומאוזן',
    tags: ['נקי', 'רענן'],
    moduleShape: 'rounded',
    eyeFrame: 'leaf',
    eyeBall: 'circle',
    dotScale: 0.96,
    body: solid('#047857'),
    eyeFramePaint: solid('#047857'),
    eyeBallPaint: solid('#065F46'),
    background: solid('#F0FDF4'),
    quietZone: 4,
    cornerRadius: 0.1,
    plate: { strokePaint: solid('#A7F3D0'), width: 0.3, inset: 1.2 },
    frameStyle: 'outline',
    frameBarPaint: solid('#F0FDF4'),
    frameTextPaint: solid('#047857'),
    ecLevel: 'Q',
    previewBg: '#F0FDF4',
  },
  {
    id: 'aurora',
    name: 'זוהר',
    blurb: 'גרדיאנט רדיאלי רב-גוני על כהה — אפקט זוהר קוטבי',
    tags: ['גרדיאנט', 'כהה', 'יצירתי'],
    moduleShape: 'fluid',
    eyeFrame: 'circle',
    eyeBall: 'circle',
    dotScale: 1,
    body: radial('#34D399', '#22D3EE', '#818CF8'),
    eyeFramePaint: solid('#34D399'),
    eyeBallPaint: solid('#818CF8'),
    background: solid('#0F172A'),
    quietZone: 4,
    cornerRadius: 0.16,
    frameStyle: 'pill',
    frameBarPaint: linear(135, '#34D399', '#818CF8'),
    frameTextPaint: solid('#0F172A'),
    ecLevel: 'Q',
    previewBg: '#0F172A',
  },
];

export const DESIGN_BY_ID = new Map(DESIGNS.map((d) => [d.id, d]));

export const DEFAULT_DESIGN = DESIGNS.find((d) => d.id === 'violet-flow') ?? DESIGNS[0];

/** כל התגיות הקיימות, לסינון בגלריה. */
export const DESIGN_TAGS = Array.from(new Set(DESIGNS.flatMap((d) => d.tags))).sort((a, b) =>
  a.localeCompare(b, 'he'),
);
